# Generated by Django 3.1.3 on 2021-03-03 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_stashes_theuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='theuser',
        ),
    ]
