# Generated by Django 3.1.3 on 2021-03-04 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0010_transactions_theuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='amount_deposited',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='stash_name',
        ),
        migrations.AddField(
            model_name='transactions',
            name='amount_of_stash',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='name_of_stash',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='deposittable',
            name='theuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stashes',
            name='theuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='theuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
