# Generated by Django 3.1.3 on 2021-03-10 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_auto_20210303_2357'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepositTable',
        ),
    ]
