# Generated by Django 3.1.3 on 2021-01-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0002_remove_testmod_wordstwo'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmod',
            name='wordstwo',
            field=models.CharField(default=22, max_length=40),
            preserve_default=False,
        ),
    ]
